name: icfpc_locator
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: san <email@example.com>

environment:
  sdk: '>=2.0.0-dev.66.0 <2.0.0'

dependencies:
  angular: ^5.0.0-beta
  angular_components: ^0.9.0-beta
  shelf:
  crypto:
  shelf_web_socket:
  google_maps:

dev_dependencies:
  build_runner: ^0.9.0
  build_web_compilers: ^0.4.0
